joint_dim: 128

image:
  _target_: model.ModalityEncoder
  output_dim: ${model.joint_dim}
  normalize: True
  encoder:
    _target_: model.ImageModel
    encoder_name: resnet50
    weights: imagenet

defaults:
  - text: bert