joint_dim: 128

image:
  _target_: model.ModalityEncoder
  output_dim: ${model.joint_dim}
  normalize: True
  encoder:
    _target_: model.ImageModel
    encoder_name: resnet50
    weights: imagenet

text:
  _target_: model.ModalityEncoder
  output_dim: ${model.joint_dim}
  normalize: True
  # encoder:
  #   _target_: model.TextModel
  #   hidden_size: 200
  #   hidden_layers: 5
  #   pretrained_bpemb_embeddings: True

  encoder:
    _target_: model.BERTModel
    model_name: 'distilbert-base-uncased'