_target_: ${model.modality_encoder}
output_dim: ${model.joint_dim}
normalize: ${model.normalize}
encoder:
  _target_: model.BERTModel
  model_name: 'DeepPavlov/distilrubert-tiny-cased-conversational'
  dropout: 0.3

# DeepPavlov/distilrubert-tiny-cased-conversational
# xlm-roberta-base
# distilbert-base-uncased
# distilrubert-base-cased-conversational